.TH GLMARK2-ES2 1 "2010-07-15"
.SH NAME
glmark2(-es2) \- OpenGL (ES) 2.0 benchmark
.SH SYNOPSIS
.B glmark2
.br
.B glmark2-es2
.SH DESCRIPTION
\fBglmark2(-es2)\fP is a benchmark for OpenGL (ES) 2.0. It only uses the subset of
the OpenGL 2.0 API that is compatible with OpenGL ES 2.0.
.SH AUTHOR
glmark2 was written by Alexandros Frantzis based on the original glmark by Ben Smith.
.PP
This manual page was written by Alexandros Frantzis <alexandros.frantzis@linaro.org>,
for the Debian project (and may be used by others).
